# Generated by Django 4.2.5 on 2023-11-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threews', '0003_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='assets/media/svg/brand-logos'),
        ),
    ]
