# Generated by Django 4.2.5 on 2023-11-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threews', '0004_sector_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='assets/media/svg/brand-logos'),
        ),
    ]
