# Generated by Django 4.2.5 on 2023-11-01 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threews', '0005_alter_sector_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_number', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('finished', 'Finished')], default='closed', max_length=10)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threews.year')),
            ],
            options={
                'ordering': ['year', 'month_name'],
            },
        ),
    ]
