# Generated by Django 4.2.5 on 2023-11-07 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threews', '0006_year_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='month',
            options={},
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='threews.month'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='threews.sector'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='threews.year'),
        ),
        migrations.AlterField(
            model_name='month',
            name='month_name',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
