# Generated by Django 4.2.5 on 2023-11-08 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threews', '0008_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='threews.sector'),
        ),
    ]
