# Generated by Django 4.2.7 on 2023-12-04 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threews', '0010_reportupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='threews.reportupload'),
        ),
    ]
